### ISSUE TITLE
Undefined array key "action"

### ISSUE THREAD

**Issue by JhumanJ** [oza75/laravel-ses-complaints#1]
Hi there, thanks for this great package. When used, we very often get this error: `Undefined array key "action"` from `/vendor/oza75/laravel-ses-complaints/src/Requests/BounceRequest.php` line 53. More [details here](https://notionforms.sentry.io/share/issue/464d1106bdb34faaab63a12bf0b0e8dc/).

Do you think this could be a mis-configuration issue on my side? Or do you have any guideline on how to resolve this?

Thanks!

**Comment by bjshirey** [comment]
> Hi there, thanks for this great package. When used, we very often get this error: `Undefined array key "action"` from `/vendor/oza75/laravel-ses-complaints/src/Requests/BounceRequest.php` line 53. More [details here](https://notionforms.sentry.io/share/issue/464d1106bdb34faaab63a12bf0b0e8dc/).
> 
> Do you think this could be a mis-configuration issue on my side? Or do you have any guideline on how to resolve this?
> 
> Thanks!

That error message appears due to a bug in this package.

Per [Amazon's documentation](https://docs.aws.amazon.com/ses/latest/dg/notification-contents.html), the "action" field is optional for a bounced recipient. However, the current implementation of the BounceRequest in this package does not properly test if the "action" field exists before trying to access it nor does it provide a fallback if the data isn't there.

**Comment by oza75** [comment]
Fixes in v0.0.5
